void resetPia6820(void);
void setKdbInterrups(int b);
int getKbdInterrups(void);
int getDspOutput(void);
void writeDspCr(unsigned char dspCr);
void writeDsp(unsigned char dsp);
void writeKbdCr(unsigned char kbdCr);
void writeKbd(unsigned char kbd);
unsigned char readDspCr(void);
unsigned char readDsp(void);
unsigned char readKbdCr(void);
unsigned char readKbd(void);
